### ISSUE TITLE
wcslib-old.rb problem?

### ISSUE THREAD

**Issue by tashley185** [ska-sa/homebrew-tap#17]
Hello, I am am trying to install Obit, but before that I need to tap ska-sa.  I am unable to tap ska-sa.  The following are the warnings/errors that I am receiving which seems to fail when it gets to the wcslib-old.rb file:   

 brew tap ska-sa/tap
==> Tapping ska-sa/tap
Cloning into '/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap'...
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 27 (delta 0), reused 13 (delta 0), pack-reused 0
Unpacking objects: 100% (27/27), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/bnmin1.rb:6:in `class:Bnmin1'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/bnmin1.rb:6:in `class:Bnmin1'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/bnmin1.rb:6:in `class:Bnmin1'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/leo.rb:6:in `class:Leo'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/leo.rb:6:in `class:Leo'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/leo.rb:6:in `class:Leo'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/leo.rb:10:in `block in class:Leo'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/leo.rb:10:in `block in class:Leo'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libair.rb:6:in `class:Libair'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libair.rb:6:in `class:Libair'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libair.rb:6:in `class:Libair'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libmodbus2.rb:6:in `class:Libmodbus2'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libmodbus2.rb:6:in `class:Libmodbus2'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libmodbus2.rb:6:in `class:Libmodbus2'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libwww.rb:6:in `class:Libwww'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libwww.rb:6:in `class:Libwww'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/libwww.rb:6:in `class:Libwww'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/openmotif.rb:6:in `class:Openmotif'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/openmotif.rb:6:in `class:Openmotif'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/openmotif.rb:6:in `class:Openmotif'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/rpfits.rb:6:in `class:Rpfits'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/rpfits.rb:6:in `class:Rpfits'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/rpfits.rb:6:in `class:Rpfits'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/sketch.rb:6:in `class:Sketch'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/sketch.rb:6:in `class:Sketch'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/sketch.rb:6:in `class:Sketch'
Please report this to the ska-sa/tap tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/wcslib-old.rb:6:in `class:Wcslib'
Please report this to the ska-sa/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/wcslib-old.rb:6:in `class:Wcslib'
Please report this to the ska-sa/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/wcslib-old.rb:6:in `class:Wcslib'
Please report this to the ska-sa/tap tap!

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/wcslib-old.rb
No available formula with the name "wcslib-old" 
In formula file: /usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/wcslib-old.rb
Expected to find class WcslibOld, but only found: Wcslib.
Error: Cannot tap ska-sa/tap: invalid syntax in tap!

**Comment by ludwigschwardt** [comment]
`wcslib-old.rb` has been removed and the Obit formula should work again. Please re-open if not the case (and sorry for the very long wait!).
