### ISSUE TITLE
brew install fails with gsl@1 dependency issue

### ISSUE THREAD

**Issue by tam116** [ska-sa/homebrew-tap#21]
==> Installing obit from ska-sa/tap
Error: No available formula with the name "gsl@1" (dependency of ska-sa/tap/obit)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
 git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps

**Comment by ludwigschwardt** [comment]
This was fixed in commit 0898111.
