### ISSUE TITLE
casacore install on OS X Mavericks

### ISSUE THREAD

**Issue by telegraphic** [ska-sa/homebrew-tap#3]
Hi there -- fantastic to see a homebrew repo with this stuff in it!

I've got a shiny new macbook and am trying to install casacore/pyrap on it. It fails however, due to OS X 10.9 defaulting to build with libc++ instead of libstdc++. I can get it to install by modifying the Cmakelist.txt to:

```
set (CMAKE_CXX_FLAGS "-W -Wall -Wpointer-arith -pedantic -Wno-long-long -stdlib=libstdc++")
```

I am, however, yet to get pyrap to install. I assume it is failing for the same reason, but I'm not sure how to force libstdc++ to be used through the batchbuild.py file...

**Comment by gijzelaerr** [comment]
this is working with the latest casacore and recipes.
