### ISSUE TITLE
openmotif on OSX mavericks10.9.3

### ISSUE THREAD

**Issue by yeeon** [ska-sa/homebrew-tap#8]
Yang-Book:scripts yyliang$ brew tap ska-sa/tap
Cloning into '/usr/local/Library/Taps/ska-sa/homebrew-tap'...
remote: Reusing existing pack: 355, done.
remote: Total 355 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (355/355), 105.52 KiB | 83.00 KiB/s, done.
Resolving deltas: 100% (204/204), done.
Checking connectivity... done.
Tapped 21 formulae
Yang-Book:scripts yyliang$ brew search motif
openmotif
Yang-Book:scripts yyliang$ brew install openmotif
==> Installing openmotif dependency: pkg-config
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/pkg-config-
###### ################################################################## 100.0%

==> Pouring pkg-config-0.28.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 604K
==> Installing openmotif
==> Downloading http://motif.ics.com/sites/default/files/openmotif-2.3.3.tar.gz
###### ################################################################## 100.0%

==> Downloading https://trac.macports.org/export/83688/trunk/dports/x11/openmoti
###### ################################################################## 100.0%

==> Downloading https://trac.macports.org/export/83688/trunk/dports/x11/openmoti
###### ################################################################## 100.0%

==> Downloading https://trac.macports.org/raw-attachment/ticket/30898/patch-demo
###### ################################################################## 100.0%

==> Downloading https://trac.macports.org/raw-attachment/ticket/30898/patch-clie
###### ################################################################## 100.0%

==> Patching
patching file lib/Xm/DragBS.c
patching file lib/Xm/DragIcon.c
patching file lib/Xm/Text.c
patching file lib/Xm/TextF.c
Hunk #1 succeeded at 7340 (offset 34 lines).
Hunk #2 succeeded at 8212 (offset 34 lines).
Hunk #3 succeeded at 10125 (offset 34 lines).
patching file lib/Xm/Protocols.c
patching file lib/Xm/VendorS.c
patching file lib/Xm/Synthetic.c
Hunk #1 succeeded at 199 (offset 2 lines).
Hunk #2 succeeded at 243 (offset 2 lines).
Hunk #3 succeeded at 518 (offset 6 lines).
patching file lib/Xm/Obso2_0.c
patching file lib/Xm/Xpmparse.c
patching file lib/Xm/SlideC.c
patching file lib/Xm/DataF.c
patching file lib/Xm/FontS.c
patching file clients/mwm/WmResParse.c
patching file lib/Xm/IconG.c
Hunk #1 succeeded at 280 (offset 1 line).
patching file clients/mwm/WmMenu.c
patching file lib/Xm/XpmI.h
patching file lib/Xm/BaseClass.c
patching file lib/Xm/XmIm.c
patching file lib/Mrm/Makefile.in
Hunk #1 succeeded at 198 (offset 31 lines).
patching file demos/programs/periodic/Makefile.in
patching file clients/uil/UilDefI.h
==> ./configure --prefix=/usr/local/Cellar/openmotif/2.3.3 --enable-xft --enable
==> make install
clang: error: unknown argument: '-fno-tree-ter' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make[2]: **\* [makestrs.o] Error 1
make[1]: **\* [install-recursive] Error 1
make: **\* [install-recursive] Error 1

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ska-sa/homebrew-tap/issues

**Comment by ludwigschwardt** [comment]
Another World Cup later... Sorry about that 😲 

Commit 92645f353 (in 2016!) removed the openmotif formula in favour of the official one in homebrew-core.
