### ISSUE TITLE
Installing casacore/pyrap on OSX Mavericks

### ISSUE THREAD

**Issue by AntoniaR** [ska-sa/homebrew-tap#9]
This issue seems to be different to the other errors identified for OSX Mavericks, although it is not clear from the error message what is failing. I have installed all the dependencies but get this error when I attempt to brew casacore. Any ideas what is going wrong? Is there a way I can get more detailed error logs?
Thanks!

<pre>
Downloads$ brew install casacore
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://casacore.googlecode.com/files/casacore-1.5.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/casacore-1.5.0.tar.bz2
==> cmake ../.. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/casacore/1.5.0 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=release -DUSE_FFTW3=ON -DFFTW3_ROOT
==> make install
make[2]: *** Waiting for unfinished jobs....
Building CXX object casa/CMakeFiles/casa_casa.dir/Quanta/MVDoppler.cc.o
cd /tmp/casacore-phHf/casacore-1.5.0/build/release/casa && /usr/local/Library/ENV/4.3/g++-4.8   -DHAVE_FFTW3 -DHAVE_FFTW3_THREADS -DHAVE_HDF5 -DHAVE_READLINE -DUSE_THREADS -Dcasa_casa_EXPORTS -W -Wall -Wpointer-arith -pedantic -Wno-long-long -pthread -O3 -DNDEBUG -fPIC -I/tmp/casacore-phHf/casacore-1.5.0 -I/tmp/casacore-phHf/casacore-1.5.0/build/release -I/usr/local/include    -o CMakeFiles/casa_casa.dir/Quanta/MVDoppler.cc.o -c /tmp/casacore-phHf/casacore-1.5.0/casa/Quanta/MVDoppler.cc
make[1]: *** [casa/CMakeFiles/casa_casa.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ska-sa/homebrew-tap/issues
</pre>

**Comment by tammojan** [comment]
See https://github.com/casacore/casacore/issues/85 , the issue with the Complex will probably be fixed in casacore 2.0

**Comment by gijzelaerr** [comment]
I think this issue has been fixed, I can succesfully build the latest casacore and python-casacore on OSX 10.11.1
